# List of durations to run the benchmark for (each duration will run sequentially)
durations = ["60s"]

# Cooldown sleep durations between benchmark runs
cooldowns = ["1s"]

# List of worker counts (number of concurrent goroutines making requests)
workers = [100, 200, 500]

# Named target HTTP servers to benchmark
[[targets]]
name = "Lamu Local Server"
url = "http://192.168.0.5:8123"


[[targets]]
name = "Django Local Server ASGI"
url = "http://192.168.0.5:8124"

[[targets]]
name = "Django Local Server WSGI"
url = "http://192.168.0.5:8125"
