# List of durations to run the benchmark for (each duration will run sequentially)
durations = ["5s", "10s", "30s", "60s"]

# Cooldown sleep durations between benchmark runs
cooldowns = ["2s", "5s"]

# List of worker counts (number of concurrent goroutines making requests)
workers = [10, 50, 100, 200, 500]

# Named target HTTP servers to benchmark
[[targets]]
name = "Lamu Local Server"
url = "http://localhost:8123"

[[targets]]
name = "Django Local Server ASGI"
url = "http://localhost:8124"

[[targets]]
name = "Django Local Server WSGI"
url = "http://localhost:8125"
