# List of durations to run the benchmark for (each duration will run sequentially)
durations = ["10s"]

# Cooldown sleep durations between benchmark runs
cooldowns = ["1s"]

# List of worker counts (number of concurrent goroutines making requests)
workers = [1, 50, 500]

# Named target HTTP servers to benchmark
[[targets]]
name = "Lariv Local Server"
url = "http://localhost:8123"

[[targets]]
name = "Django Local Server ASGI"
url = "http://localhost:8124"

[[targets]]
name = "Django Local Server WSGI"
url = "http://localhost:8125"

[[targets]]
name = "Odoo Local Server"
url = "http://localhost:8126"
